### ISSUE TITLE
bsz-cui-extras: Could not load pixelbuster library 'libpixelbuster.so' for platform 'linux'

### ISSUE THREAD

**Issue by DarkAlchy** [Beinsezii/pixelbuster#1]
bsz-cui-extras: Could not load pixelbuster library 'libpixelbuster.so' for platform 'linux'
bsz-cui-extras: Consider downloading the appropriate pixelbuster library for your platform from
bsz-cui-extras: https://github.com/Beinsezii/pixelbuster

bsz-cui-extras: Failed to load 'bsz-pixelbuster' module
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/generalawareness/comfyui/custom_nodes/bsz-cui-extras/bsz-nodes/libpixelbuster.so)

I went looking and the best I could find is Ubuntu22.04 is built into the OS is 2.35.

**Comment by Beinsezii** [comment]
Can install a newer glib from here

https://ftp.gnu.org/gnu/glibc/

Or alternatively, downloading a different libpixelbuster from GitHub Actions artifacts may work

https://github.com/Beinsezii/pixelbuster/actions/workflows/build_release_master.yml

**Comment by DarkAlchy** [comment]
I'll try that as I am currently installing Kohya, and ended up in dependency hell.  I got comfy up and working except for this lone package.

**Comment by DarkAlchy** [comment]
Not happening.

mkdir $HOME/glibc/ && cd $HOME/glibc
wget http://ftp.gnu.org/gnu/libc/glibc-2.32.tar.gz
tar -xvzf glibc-2.32.tar.gz
mkdir build 
mkdir glibc-2.32-install
cd build
~/glibc/glibc-2.32/configure --prefix=$HOME/glibc/glibc-2.32-install
make
make install

Did all of that (changing .32 with the required .38) without a hitch, but it still complains of not having 2.38.

**Comment by Beinsezii** [comment]
Try the pixel buster built with GitHub Actions I linked. Their boxes are Ubuntu.

Just replace the existing libpixelbuster.so file

**Comment by DarkAlchy** [comment]
Worked like a charm.

Thank you.
